version: '3'

services:
  app:
    image: ompugao/colmap
    build: 
      context: .
      dockerfile: Dockerfile
    userns_mode: "host"
    network_mode: host
    ipc: "host"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [compute, gpu, utility, graphics]
    privileged: true
    environment:
      XAUTHORITY: ${XAUTH}
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
    volumes:
      # - ../capturedhands/:/capturedhands:cached
      - .:/workspace:cached
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ${XAUTH}:${XAUTH}:ro
